application: accident-response
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico,aars_logo.png,bk.png,bk_gd.jpg
  upload: favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
